sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t radhakrishna1979/react-test -f ./client/Dockerfile.dev ./client
    
script:
  - docker run -e CI=true radhakrishna1979/react-test npm test

after_success:
  - docker build -t kommera1979/rk-client ./client
  - docker build -t kommera1979/rk-server ./server
  - docker build -t kommera1979/rk-nginx  ./nginx
  - docker build -t kommera1979/rk-worker ./worker

  - echo "$DOCKER_PASSWORD"  |  docker login -u "$DOCKER_ID" --password-std-in
  - docker push kommera1979/rk-client
  - docker push kommera1979/rk-server
  - docker push kommera1979/rk-nginx
  - docker push kommera1979/rk-worker
  